version: '3.8'

# Production overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  postgres:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-change_this_in_production}"

  redis:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD:-change_this_in_production}"

  app:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      NODE_ENV: production
      LOG_LEVEL: warn
      DATABASE_URL: "postgresql://secretly_user:${POSTGRES_PASSWORD:-change_this_in_production}@postgres:5432/secretly"
      REDIS_URL: "redis://:${REDIS_PASSWORD:-change_this_in_production}@redis:6379"

  # Remove development tools
  pgadmin:
    deploy:
      replicas: 0

  redis-commander:
    deploy:
      replicas: 0