name: ojo

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
      - uses: colibrisec/ojo-action@a7c5469668eaf34edff10ab3f1119475596c0f2f # v1.1.2

      - name: Upload to Balam
        if: ${{ always() && github.event_name != 'pull_request' && hashFiles('ojo-report.json') != '' }}
        uses: colibrisec/balam-action@88a6df7e085a860ea6d11719789bb197807c0402 # v1
        with:
          file: ojo-report.json
          scan-type: 'OJO Scan'
          balam-url: ${{ secrets.BALAM_URL }}
          balam-token: ${{ secrets.BALAM_TOKEN }}
          product-name: secretly
          engagement-name: 'CI Scans'
